# Generated by Django 6.1.1 on 2026-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_workspace_document_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
